# Generated by Django 3.0.3 on 2020-03-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stagaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intitule', models.CharField(choices=[('Technicien spécialisé', 'Technicien spécialisé'), ('Technicien', 'Technicien'), ('Qualification', 'Qualification'), ('Spécialisation', 'Spécialisation'), ('Formation Qualifiante', 'Formation Qualifiante')], default='Technicien spécialisé', max_length=150)),
            ],
        ),
    ]
