# Generated by Django 3.0.3 on 2020-03-21 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stagaire', '0003_stagaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateDebut', models.DateField()),
                ('DateFin', models.DateField()),
                ('Societe', models.CharField(max_length=150)),
                ('Rapport', models.FileField(blank=True, null=True, upload_to='')),
                ('stagaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stagaire.Stagaire')),
            ],
        ),
    ]
