# Generated by Django 3.0.3 on 2020-03-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stagaire', '0004_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagaire',
            name='dateDeNaissance',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
