# Generated by Django 3.0.3 on 2020-03-23 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stagaire', '0005_auto_20200323_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagaire',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stagaire.Filiere'),
        ),
        migrations.AlterField(
            model_name='stagaire',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='stagaire',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stagaire.Niveau'),
        ),
        migrations.AlterField(
            model_name='stagaire',
            name='nom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stagaire',
            name='prenom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
