# Generated by Django 3.0.3 on 2020-03-24 23:16

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Stagaire', '0006_auto_20200323_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagaire',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
