# Generated by Django 3.0.3 on 2020-03-24 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stagaire', '0007_auto_20200325_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagaire',
            name='usern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
