# Generated by Django 3.0.3 on 2020-03-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stagaire', '0008_stagaire_usern'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagaire',
            name='StagaireSlug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='StageSlug',
            field=models.SlugField(blank=True),
        ),
    ]
