# Generated by Django 3.0.4 on 2020-03-30 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stagaire', '0009_auto_20200326_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagaire',
            name='usern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
