# Generated by Django 3.0.4 on 2020-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stagaire', '0011_auto_20200331_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='Secteur',
            field=models.CharField(choices=[('Actions Sociales', 'Actions Sociales'), ('Administration Gestion et Commerce', 'Administration Gestion et Commerce'), ('Aéronautique', 'Aéronautique'), ('Agroalimentaire', 'Agroalimentaire'), ('Arts graphiques', 'Arts graphiques'), ('Arts traditionnels', 'Arts traditionnels'), ('Audio visuel et cinéma', 'Audio visuel et cinéma'), ('Bâtiment et Travaux Pub1lics', 'Bâtiment et Travaux Publics'), ('Construction Métallique', 'Construction Métallique'), ('Cuir et modélisme', 'Cuir et modélisme'), ('Fabrication Mécanique', 'Fabrication Mécanique'), ('Froid et Génie Thermique', 'Froid et Génie Thermique'), ('Génie Électrique', 'Génie Électrique'), ('Industrie de l’automobile', 'Industrie de l’automobile'), ('Offshoring', 'Offshoring'), ('Plasturgie', 'Plasturgie'), ('Technologies de l’information', 'Technologies de l’information'), ('Textile et Habillement', 'Textile et Habillement'), ('Tourisme et Hôtellerie', 'Tourisme et Hôtellerie'), ('Transport et logistique', 'Transport et logistique')], default='Actions Sociales', max_length=250),
        ),
    ]
