# Generated by Django 3.0.4 on 2020-04-14 19:47

import Stagaire.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stagaire', '0012_auto_20200402_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='Rapport',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[Stagaire.validators.validate_file_extension]),
        ),
    ]
